repos:
  - repo: local
    hooks:
      - id: end-of-file-fixer
        name: End of File Fixer
        entry: end-of-file-fixer
        language: system
        types: [file]

      - id: trailing-whitespace
        name: Trailing Whitespace
        entry: trailing-whitespace-fixer
        language: system
        types: [file]

      - id: semgrep-security-scan
        name: Local Semgrep Scan
        entry: semgrep --config auto
        language: system
        files: \.(py|js|ts|go)$
